defaults: &defaults
  autocreate_indexes: false
  allow_dynamic_fields: false
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3
  skip_version_check: true

development:
  <<: *defaults
  host: localhost
  port: 27017
  database: grokphoto_development

test:
  <<: *defaults
  host: localhost
  port: 27017
  database: grokphoto_test

# set these environment variables on your prod server
production:
  host: flame.mongohq.com
  port: 27083
  database: grokphoto
